/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/checks/s21_polish_calc_check.check"
 * instead.
 */

#include <check.h>
#include <stdio.h>
#include <stdlib.h>

#define CORRECT_STR 0
#define INCORRECT_STR 1

#include "../backend/s21_smartcalc.h"

START_TEST(polish_calc_1) {
  char input[255] = "2+2*2";
  long double rez = 0;
  long double x_value = 0;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(2 + 2 * 2, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_2) {
  char input[255] = "cos(30)";
  long double rez = 0;
  long double x_value = 0;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(cos(30), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_3) {
  char input[255] = "sin(30)";
  long double rez = 0;
  long double x_value = 0;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(sin(30), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_4) {
  char input[255] = "tan(30)";
  long double rez = 0;
  long double x_value = 0;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(tan(30), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_5) {
  char input[255] = "acos(0.5)";
  long double rez = 0;
  long double x_value = 0;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(acos(0.5), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_6) {
  char input[255] = "asin(0.3)";
  long double rez = 0;
  long double x_value = 0;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(asin(0.3), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_7) {
  char input[255] = "atan(-0.3)";
  long double rez = 0;
  long double x_value = 0;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(atan(-0.3), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_8) {
  char input[255] = "sqrt(0.7)";
  long double rez = 0;
  long double x_value = 0;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(sqrt(0.7), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_9) {
  char input[255] = "ln(30)";
  long double rez = 0;
  long double x_value = 0;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(log(30), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_10) {
  char input[255] = "log(30)";
  long double rez = 0;
  long double x_value = 0;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(log10(30), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_11) {
  char input[255] = "2+7";
  long double rez = 0;
  long double x_value = 0;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(2 + 7, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_12) {
  char input[255] = "9146-5752";
  long double rez = 0;
  long double x_value = 0;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(9146 - 5752, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_13) {
  char input[255] = "3*(5*x+5)+1";
  long double rez = 0;
  long double x_value = 4;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(3 * (5 * 4 + 5) + 1, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_14) {
  char input[255] = "4*(2*x+2)+5*(3*x-5)";
  long double rez = 0;
  long double x_value = 3;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(4 * (2 * 3 + 2) + 5 * (3 * 3 - 5), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_15) {
  char input[255] = "5^(ln(3))";
  long double rez = 0;
  long double x_value = 0;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(pow(5, log(3)), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_16) {
  char input[255] = "sin(5)*12";
  long double rez = 0;
  long double x_value = 0;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(sin(5) * 12, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_17) {
  char input[255] = "cos(x)^2+sin(x)^2";
  long double rez = 0;
  long double x_value = 7;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(pow(cos(x_value), 2) + pow(sin(x_value), 2), rez,
                           1e-7);
}
END_TEST

START_TEST(polish_calc_18) {
  char input[255] = "568784864764864-8764584+6*87648";
  double rez = 0;
  double x_value = 7;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(568784864764864 - 8764584 + 6 * 87648, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_19) {
  char input[255] = "sqrt(-1)";
  long double x_value = 7;
  int error = 0;
  s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(1, error);
}
END_TEST

START_TEST(polish_calc_20) {
  char input[255] = "log(-1)";
  long double x_value = 7;
  int error = 0;
  s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(1, error);
}
END_TEST

START_TEST(polish_calc_21) {
  char input[255] = "ln(-1)";
  long double x_value = 7;
  int error = 0;
  s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(1, error);
}
END_TEST

START_TEST(polish_calc_22) {
  char input[255] = "asin(2)";
  long double x_value = 7;
  int error = 0;
  s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(1, error);
}
END_TEST

START_TEST(polish_calc_23) {
  char input[255] = "acos(3)";
  long double x_value = 7;
  int error = 0;
  s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(1, error);
}
END_TEST

START_TEST(polish_calc_24) {
  char input[255] = "asin(1)";
  long double rez = 0;
  long double x_value = 7;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(asin(1), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_25) {
  char input[255] = "acos(1)";
  long double rez = 0;
  long double x_value = 7;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(acos(1), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_26) {
  char input[255] = "atan(5*7)^(ln(65/46))/tan(89*76)*tan(06-60)-atan(56*67)";
  double rez = 0;
  double x_value = 7;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(
      pow(atan(5 * 7), log(65.0 / 46.0)) / tan(89 * 76) * tan(06 - 60) -
          atan(56 * 67),
      rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_27) {
  char input[255] = "atan(5*7)";
  long double rez = 0;
  long double x_value = 7;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(atan(5 * 7), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_28) {
  char input[255] = "log(65/46)";
  long double rez = 0;
  long double x_value = 7;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(log10(65.0 / 46.0), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_29) {
  char input[255] = "atan(5*7)^(ln(65/46))";
  long double rez = 0;
  long double x_value = 7;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(pow(atan(5 * 7), log(65.0 / 46.0)), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_30) {
  char input[255] = "sqrt(008*3550)";
  long double rez = 0;
  long double x_value = 7;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(sqrt(8 * 3550), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_31_0) {
  char input[255] =
      "sqrt(008*3550)^(cos(80780*568097))/ln(6*6)^((asin(50/"
      "2807640))^cos(665*867))";
  double rez = 0;
  double x_value = 7;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_double_eq_tol(
      pow(sqrt(8 * 3550), cos(80780.0 * 568097.0)) /
          pow(pow(log(6 * 6), asin(50.0 / 2807640.0)), cos(665.0 * 867)),
      rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_31_1) {
  char input[255] = "ln(6*6)^(asin(50/2807640))^(cos(665*867))";
  double rez = 0;
  double x_value = 7;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(
      pow(pow(log(6.0 * 6.0), asin(50.0 / 2807640.0)), cos(665.0 * 867.0)), rez,
      1e-7);
}
END_TEST

START_TEST(polish_calc_31_2) {
  char input[255] = "ln(6*6)^(asin(50/2807640))";
  long double rez = 0;
  long double x_value = 7;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(powl(logl(6.0L * 6.0L), asinl(50.0L / 2807640.0L)),
                           rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_31_3) {
  char input[255] = "1.000023^(cos(665*867))";
  long double rez = 0;
  long double x_value = 7;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(powl(1.000023L, cosl(665.0L * 867.0L)), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_35) {
  char input[255] = "ln(6*6)";
  long double rez = 0;
  long double x_value = 7;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(logl(6 * 6), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_36) {
  char input[255] = "ln(6*6)^15392.675975";
  long double rez = 0;
  long double x_value = 7;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_double_eq(pow(logl(6 * 6), 15392.675975), rez);
}
END_TEST

START_TEST(polish_calc_37) {
  char input[255] = "sqrt(008*3550)^(cos(80780*568097))";
  long double rez = 0;
  long double x_value = 7;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(pow(sqrt(8 * 3550), cos(80780.0 * 568097.0)), rez,
                           1e-7);
}
END_TEST

START_TEST(polish_calc_38) {
  char input[255] =
      "asin(836-65954)^(ln(0*67)^(tan(59687*22678)))/"
      "cos(73953*0078)^(log(2288623*2656607))";
  long double x_value = 7;
  int error = 0;
  s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(1, error);
}
END_TEST

START_TEST(polish_calc_39) {
  char input[255] = "log(2^8)-sqrt(6/2)/asin(0.3)-sin(75*8484)/log(96^3908)";
  long double rez = 0;
  long double x_value = 7;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(
      log10l(powl(2.0L, 8.0L)) - sqrtl(6.0L / 2.0L) / asinl(0.3L) -
          sinl(75.0L * 8484.0L) / log10l(powl(96.0L, 3908.0L)),
      rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_40) {
  char input[255] = "-3^3.2";
  long double x_value = 7;
  int error = 0;
  s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
}
END_TEST

START_TEST(polish_calc_41) {
  char input[255] = "0^(-3.2)";
  long double x_value = 7;
  int error = 0;
  s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(1, error);
}
END_TEST

START_TEST(polish_calc_42) {
  char input[255] = "5+(+5)";
  long double rez = 0;
  long double x_value = 7;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(10, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_43) {
  char input[255] = "5+(-5)";
  long double rez = 0;
  long double x_value = 7;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(0, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_44) {
  char input[255] = "5 + x";
  long double rez = 0;
  long double x_value = 56;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(61, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_45) {
  char input[255] = "5-(-5)";
  long double rez = 0;
  long double x_value = 56;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(10, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_46) {
  char input[255] = "5-(-+-5)";
  long double rez = 0;
  long double x_value = 56;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(0, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_47) {
  char input[255] = "7^(asin(x/4 + 0.3) / tan(2*x/3))";
  double rez = 0;
  double x_value = 1.2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_double_eq_tol(
      pow(7, (asin(x_value / 4.0 + 0.3) / tan(2 * x_value / 3))), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_47_1) {
  char input[255] = "asin(x/4 + 0.3)";
  double rez = 0;
  double x_value = 1.2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_double_eq_tol(asin(x_value / 4.0 + 0.3), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_47_2) {
  char input[255] = "x/4 + 0.3";
  double rez = 0;
  double x_value = 1.2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_double_eq_tol(x_value / 4.0 + 0.3, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_48) {
  char input[255] = "sin(20mod3.5)";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(0.598472144104L, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_49) {
  char input[255] = "asin(1)";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(asin(1), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_50) {
  char input[255] = "10-23*(-27+1)";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(608, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_51) {
  char input[255] = "5-(-5)";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(10, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_52) {
  char input[255] = "-cos(9)";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(0.911130261885L, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_53) {
  char input[255] = "sin(9)-(--2)";
  double rez = 0;
  double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_double_eq_tol((sin(9) - (- -2)), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_54) {
  char input[255] = "sin(9)-(-2)";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(2.412118485242L, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_55) {
  char input[255] = "(-10)+10";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(0L, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_56) {
  char input[255] = "(-2.2)-2.2";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(-4.4L, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_57) {
  char input[255] = "(-5.6)/5.6";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(-1L, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_58) {
  char input[255] = "(2.6)^(-2.6)+-1";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(-0.9166185784040606L, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_59) {
  char input[255] = "cos(+5)";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(0.283662185463L, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_60) {
  char input[255] = "tan(2)";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(-2.185039863262L, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_61) {
  char input[255] = "-21";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(-21.0L, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_62) {
  char input[255] = "21";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(21.0L, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_63) {
  char input[255] = "tan(--tan(10)+tan(10))";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(3.5568216653650L, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_64) {
  char input[255] = "-cos(cos(21))";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(-0.853709209803L, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_65) {
  char input[255] = "log(5 mod 10)";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(0.6989700043360189L, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_66) {
  char input[255] = "cos(sin(atan(25) + 2))";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(0.928860543409L, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_67) {
  char input[255] = "cos(sin(atan(+-25) + 2))";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(0.899506721076L, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_67_1) {
  char input[255] = "atan(+-25)";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(atan(-25.0), rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_68) {
  char input[255] = "cos(sin(atan(+--25) + 2))";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(0.928860543409L, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_69) {
  char input[255] = "+2-(-10)";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(12.0L, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_70) {
  char input[255] = "12-6+(--6)";
  long double rez = 0;
  long double x_value = 2;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(12.0L, rez, 1e-7);
}
END_TEST

START_TEST(polish_calc_71) {
  char input[255] = "12/(6-(--6))";
  long double x_value = 2;
  int error = 0;
  s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(1, error);
}
END_TEST

START_TEST(polish_calc_73) {
  char input[255] = "cos(sin(atan(+++25) + 2))";
  long double x_value = 2;
  long double rez = 0;
  int error = 0;
  rez = s21_smart_calc_func(input, x_value, &error);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(0.9288605434090L, rez, 1e-7);
}
END_TEST

START_TEST(validator_test_1) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "2+2";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_2) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "2 + 2 - cos(20)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_3) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "2 + 2 - cos(20) * (log(10) mod 5 + 3)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_4) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "(log(10) mod 5 + 3)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_5) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "log(1) mod 5 ";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_6) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "2 + 2 - cos(20) * (log(10) mod (-5) + 3)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_7) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "2 + 2 - cos(20) * (log(10)- mod (-5) + 3)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(INCORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_8) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "2 + 2 - cos(20) * (-log(10) mod (-5) + 3)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_9) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "sin(ln(20)) * 2 + 2 - cos(20) * (-log(10) mod (-5) + 3)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_10) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "ln(20)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_11) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "3 + 4 * (2 - 1)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_12) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "3 + 4 * (2 - 1)^log(1)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_13) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "3 + 4 * (2 - 1)(^log(1)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(INCORRECT_STR, status);
}
END_TEST

START_TEST(validator_test_14) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "cos(5) + sin(2 + 3) - 0 + tan(3 * sqrt(4))";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_15) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "acos(2 + 3) mod asin(2)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_16) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "asin(2)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_17) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "sin(2)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_18) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "acos(2)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_19) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "atan(2) + ln(25 + log(3)) * 3";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_20) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "atan(2) + ln(25 + log(3)) * 3";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_21) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "atan(2) + ln(25 + lg(3)( * 3";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(INCORRECT_STR, status);
}
END_TEST

START_TEST(validator_test_22) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "(8+2*5)/(1+3*2-4)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_23) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "(8+2*5)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_24) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "(1+3*2-4)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_25) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "5x-9";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(INCORRECT_STR, status);
}
END_TEST

START_TEST(validator_test_26) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "5.x-9";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(INCORRECT_STR, status);
}
END_TEST

START_TEST(validator_test_29) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "5mod5";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_30) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "5mod";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(INCORRECT_STR, status);
}
END_TEST

START_TEST(validator_test_31) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "sin";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(INCORRECT_STR, status);
}
END_TEST

START_TEST(validator_test_32) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "5 mod (+1)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_33) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "(mod5)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(INCORRECT_STR, status);
}
END_TEST

START_TEST(validator_test_34) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "5--5";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_35) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "5-(-5)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_36) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "5-(-+-5)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_36_6) {
  int status = 0;
  int status_dot = 0;
  char input[256] = ".+m)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(INCORRECT_STR, status);
}
END_TEST

START_TEST(validator_test_37) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "-(g(i(a(20.01)+3/25*n(2))/30m(2.5mod2))^q(5)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(INCORRECT_STR, status);
}
END_TEST

START_TEST(validator_test_38) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "7^asin(x/4 + 0.3)/tan(2*x/3)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_39) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "sin(20mod3.5)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_40) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "asin(1)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_41) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "10-23*(-27+1)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_42) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "/21";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(INCORRECT_STR, status);
}
END_TEST

START_TEST(validator_test_43) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "(2.6)^(-2.6)+-1";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_44) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "cos(+5)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_45) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "tan(--tan(10)+tan(10))";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(CORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_46) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "log(mod 3)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(INCORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_47) {
  int status = 0;
  int status_dot = 0;
  char input[256] = "(mod)";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  status = s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(INCORRECT_STR, status);
  ck_assert_int_eq(CORRECT_STR, status_dot);
}
END_TEST

START_TEST(validator_test_49) {
  int status_dot = 0;
  char input[256] = "5.....5 + 4.....4";
  Node *base = NULL;
  Node *base_reverse = NULL;
  double x_value = 0;
  ParserToStack(input, &base, x_value, &status_dot);
  ReverseStackAndSearchUnarOp(base, &base_reverse);
  s21_str_validator(base_reverse);
  DestroyStack(&base_reverse);
  DestroyStack(&base);
  ck_assert_int_eq(INCORRECT_STR, status_dot);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, polish_calc_1);
  tcase_add_test(tc1_1, polish_calc_2);
  tcase_add_test(tc1_1, polish_calc_3);
  tcase_add_test(tc1_1, polish_calc_4);
  tcase_add_test(tc1_1, polish_calc_5);
  tcase_add_test(tc1_1, polish_calc_6);
  tcase_add_test(tc1_1, polish_calc_7);
  tcase_add_test(tc1_1, polish_calc_8);
  tcase_add_test(tc1_1, polish_calc_9);
  tcase_add_test(tc1_1, polish_calc_10);
  tcase_add_test(tc1_1, polish_calc_11);
  tcase_add_test(tc1_1, polish_calc_12);
  tcase_add_test(tc1_1, polish_calc_13);
  tcase_add_test(tc1_1, polish_calc_14);
  tcase_add_test(tc1_1, polish_calc_15);
  tcase_add_test(tc1_1, polish_calc_16);
  tcase_add_test(tc1_1, polish_calc_17);
  tcase_add_test(tc1_1, polish_calc_18);
  tcase_add_test(tc1_1, polish_calc_19);
  tcase_add_test(tc1_1, polish_calc_20);
  tcase_add_test(tc1_1, polish_calc_21);
  tcase_add_test(tc1_1, polish_calc_22);
  tcase_add_test(tc1_1, polish_calc_23);
  tcase_add_test(tc1_1, polish_calc_24);
  tcase_add_test(tc1_1, polish_calc_25);
  tcase_add_test(tc1_1, polish_calc_26);
  tcase_add_test(tc1_1, polish_calc_27);
  tcase_add_test(tc1_1, polish_calc_28);
  tcase_add_test(tc1_1, polish_calc_29);
  tcase_add_test(tc1_1, polish_calc_30);
  tcase_add_test(tc1_1, polish_calc_31_0);
  tcase_add_test(tc1_1, polish_calc_31_1);
  tcase_add_test(tc1_1, polish_calc_31_2);
  tcase_add_test(tc1_1, polish_calc_31_3);
  tcase_add_test(tc1_1, polish_calc_35);
  tcase_add_test(tc1_1, polish_calc_36);
  tcase_add_test(tc1_1, polish_calc_37);
  tcase_add_test(tc1_1, polish_calc_38);
  tcase_add_test(tc1_1, polish_calc_39);
  tcase_add_test(tc1_1, polish_calc_40);
  tcase_add_test(tc1_1, polish_calc_41);
  tcase_add_test(tc1_1, polish_calc_42);
  tcase_add_test(tc1_1, polish_calc_43);
  tcase_add_test(tc1_1, polish_calc_44);
  tcase_add_test(tc1_1, polish_calc_45);
  tcase_add_test(tc1_1, polish_calc_46);
  tcase_add_test(tc1_1, polish_calc_47);
  tcase_add_test(tc1_1, polish_calc_47_1);
  tcase_add_test(tc1_1, polish_calc_47_2);
  tcase_add_test(tc1_1, polish_calc_48);
  tcase_add_test(tc1_1, polish_calc_49);
  tcase_add_test(tc1_1, polish_calc_50);
  tcase_add_test(tc1_1, polish_calc_51);
  tcase_add_test(tc1_1, polish_calc_52);
  tcase_add_test(tc1_1, polish_calc_53);
  tcase_add_test(tc1_1, polish_calc_54);
  tcase_add_test(tc1_1, polish_calc_55);
  tcase_add_test(tc1_1, polish_calc_56);
  tcase_add_test(tc1_1, polish_calc_57);
  tcase_add_test(tc1_1, polish_calc_58);
  tcase_add_test(tc1_1, polish_calc_59);
  tcase_add_test(tc1_1, polish_calc_60);
  tcase_add_test(tc1_1, polish_calc_61);
  tcase_add_test(tc1_1, polish_calc_62);
  tcase_add_test(tc1_1, polish_calc_63);
  tcase_add_test(tc1_1, polish_calc_64);
  tcase_add_test(tc1_1, polish_calc_65);
  tcase_add_test(tc1_1, polish_calc_66);
  tcase_add_test(tc1_1, polish_calc_67);
  tcase_add_test(tc1_1, polish_calc_67_1);
  tcase_add_test(tc1_1, polish_calc_68);
  tcase_add_test(tc1_1, polish_calc_69);
  tcase_add_test(tc1_1, polish_calc_70);
  tcase_add_test(tc1_1, polish_calc_71);
  tcase_add_test(tc1_1, polish_calc_73);

  tcase_add_test(tc1_1, validator_test_1);
  tcase_add_test(tc1_1, validator_test_2);
  tcase_add_test(tc1_1, validator_test_3);
  tcase_add_test(tc1_1, validator_test_4);
  tcase_add_test(tc1_1, validator_test_5);
  tcase_add_test(tc1_1, validator_test_6);
  tcase_add_test(tc1_1, validator_test_7);
  tcase_add_test(tc1_1, validator_test_8);
  tcase_add_test(tc1_1, validator_test_9);
  tcase_add_test(tc1_1, validator_test_10);
  tcase_add_test(tc1_1, validator_test_11);
  tcase_add_test(tc1_1, validator_test_12);
  tcase_add_test(tc1_1, validator_test_13);
  tcase_add_test(tc1_1, validator_test_14);
  tcase_add_test(tc1_1, validator_test_15);
  tcase_add_test(tc1_1, validator_test_16);
  tcase_add_test(tc1_1, validator_test_17);
  tcase_add_test(tc1_1, validator_test_18);
  tcase_add_test(tc1_1, validator_test_19);
  tcase_add_test(tc1_1, validator_test_20);
  tcase_add_test(tc1_1, validator_test_21);
  tcase_add_test(tc1_1, validator_test_22);
  tcase_add_test(tc1_1, validator_test_23);
  tcase_add_test(tc1_1, validator_test_24);
  tcase_add_test(tc1_1, validator_test_25);
  tcase_add_test(tc1_1, validator_test_26);
  tcase_add_test(tc1_1, validator_test_29);
  tcase_add_test(tc1_1, validator_test_30);
  tcase_add_test(tc1_1, validator_test_31);
  tcase_add_test(tc1_1, validator_test_32);
  tcase_add_test(tc1_1, validator_test_33);
  tcase_add_test(tc1_1, validator_test_34);
  tcase_add_test(tc1_1, validator_test_35);
  tcase_add_test(tc1_1, validator_test_36);
  tcase_add_test(tc1_1, validator_test_36_6);
  tcase_add_test(tc1_1, validator_test_37);
  tcase_add_test(tc1_1, validator_test_38);
  tcase_add_test(tc1_1, validator_test_39);
  tcase_add_test(tc1_1, validator_test_40);
  tcase_add_test(tc1_1, validator_test_41);
  tcase_add_test(tc1_1, validator_test_42);
  tcase_add_test(tc1_1, validator_test_43);
  tcase_add_test(tc1_1, validator_test_44);
  tcase_add_test(tc1_1, validator_test_45);
  tcase_add_test(tc1_1, validator_test_46);
  tcase_add_test(tc1_1, validator_test_47);
  tcase_add_test(tc1_1, validator_test_49);

  srunner_set_fork_status(sr, CK_NOFORK);
  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
